name: TSCTutorial
author: AlonsoAliaga
version: 1.0
main: com.alonsoaliaga.tscplugin.Main
description: Tsc videos
commands:
  adisguise:
    usage: /adisguise
    description: Command to disguise